server:
   port: 9999
   context-path: "/activiti-app"
liquibase:
   enabled: false
spring:
  freemarker:
    check-template-location: false
  datasource:
    name: root
    password: root
    url:  jdbc:mysql://localhost:3306/activity?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: trace
